# Example configuration file for model training and evaluation
# Copy this file and edit the values as needed for your environment and experiments.

# --- General Training Settings ---
accumulation_steps: 16
attention_resc: 2
batch_size: 8
clinical_encoding_dim: 4
clinical_features: True
clinical_input_dim: 4
dropout: 0.25
early_stopping_patience: 70
epochs: 1
feature_extractor: "google-32"
learning_rate: 0.0001
loss_function: 'WBCE'
num_classes: 1
num_heads: 4
optimizer: 'adamW'
scheduler_gamma: 0.5
scheduler_patience: 60
scheduler_step: 5
scheduler_type: 'step'
weight_decay: 1.0e-6

# --- Data Paths ---
# Set these to the correct locations for your data files
train_paths: '/home/ffati/UnderXAI-OVIT/ds.json'  # e.g., './data/train_dataset_ids.json'
val_paths: '/home/ffati/UnderXAI-OVIT/ds.json'      # e.g., './data/val_dataset_ids.json'
test_paths: '/home/ffati/UnderXAI-OVIT/ds.json'    # e.g., './data/test_dataset_ids.json'

